"https://www.coursera.org/learn/python-osnovy-programmirovaniya/programming/PWIkw/kolichiestvo-razlichnykh-chisiel"
print(
    len(
        set(
            map(
                int,
                input().split()
                )
            )
        )
    )
